spring:
  application:
    name: eureka-server
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    # 是否从eureka上获取注册信息
    fetch-registry: false
    # 表示是否注册自身到eureka服务器
    register-with-eureka: false